import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-experience',
  templateUrl: './experience.component.html',
  styleUrls: ['./experience.component.scss'],
})
export class ExperienceComponent implements OnInit {
  experienceList = [
    {
      companyName: 'ResMed',
      companyLink: 'https://www.resmed.com/en-us/',
      companyLocation: 'San Diego, California',
      position: 'Software Engineer Intern',
      duration: 'Jun 2024 - Present',
      workItems: [
        'Built React UI from scratch and configured serverless AWS Lambdas to streamline the billing system for the Mulitcare product',
        'Implemented observability features to enhance operational visibility across 12 Node.js and Spring Boot microservices',
        'Integrated OpenTelemetry distributed tracing, resulting in a 70% reduction in production bug detection time',
        'Developed dynamic dashboards using Datadog and AWS CloudWatch to monitor logs, metrics, traces, and provide real-time alerts'
      ],
      technologyUsed: [
        'JavaScript',
        'React', 
        'Node.js', 
        'Express', 
        'Java', 
        'Spring', 
        'AWS Lambda', 
        'API Gateway', 
        'OpenTelemetry', 
        'Datadog',
        'AWS VPC',
        'AWS IAM',
        'AWS Cloudwatch',
        'AWS X-Ray'
      ],
    },
    {
      companyName: 'University of California, Davis',
      companyLink: 'https://www.ucdavis.edu/',
      companyLocation: 'California',
      position: 'Graduate Student Researcher',
      duration: 'Sep 2023 - Present',
      workItems: [
        'Designed a robust ML pipeline by building Node.js and Express backend for real-time pulse data collection, processing, MySQL storage',
        'Developed React frontend for displaying silent heart attack predictions and integrating Highcharts for visualizing 12-lead ECG waveforms',
        'Developed CNN 1D model for detecting silent heart attack, achieving a notable accuracy of 91% using 12 lead ECG data',
        'Built a robust ML pipeline to extract features from 12 lead ECG using neurokit and apply classical ML algorithms such as random forests, logistic regression, support vector machine (SVM) classifier to detect silent heart attack',
        'Implemented random forest model with an accuracy of 87% and AUROC of 93% for identifying pregnancy state',
        'Employed optimization techniques such as RFE and PCA to eliminate and transform features extracted'
      ],
      technologyUsed: [
        'Python',
        'Tensorflow',
        'Keras',
        'Pytorch',
        'sklearn',
        'matplotlib',
        'MySQL',
        'Sequelize',
        'React',
        'Node.js',
        'Express',
        'ONNX'
      ],
    },
    {
      companyName: 'University of California, Davis',
      companyLink: 'https://www.ucdavis.edu/',
      companyLocation: 'California',
      position: 'Graduate Teaching Assistant',
      duration: 'Sep 2023 - Dec 2023',
      workItems: [
        'Facilitated the learning of C++ and Arduino programming for 50 undergraduate students, fostering a dynamic and engaging educational environment as a Teaching Assistant',
        'Guided students in mastering engineering design principles, prototyping, research paper writing, and the creation of engineering design posters',
      ],
      technologyUsed: [
        'C++',
        'Arduino',
        'Software Engineering',
        'Software Engineering Research',
        'Software Engineering and Development',
        'Research Posters and Papers',
      ],
    },
    {
      companyName: 'DeepIntent',
      companyLink: 'https://www.deepintent.com/',
      companyLocation: 'Pune, India',
      position: 'Senior Software Engineer',
      duration: 'May 2021 - Aug 2023',
      workItems: [
        'Responsible for the development of efficient features in healthcare adtech platforms by following agile methodologies from scratch',
        'Contributed to modernizing the UI components across all the products and migrating existing node.js service to spring boot',
        'Worked on various research task POCs, creating design documents for new business features and developing standard pattern lib',
        'Revamped the existing data grid with ag-grid, worked on virtualised lists, pagination, react-beautiful-dnd, lazy loading and infinite scroll to improve the application performance significantly',
        'Recognized for building and scaling Node.js and Spring Boot GraphQL microservices, developed for the core campaign creation flow',
        'Responsible for taking interviews and making potential hiring decisions',
        'Previously working as a product-line head, responsible for gathering requirements, determining technical feasibility, developing proof of concepts based on research findings and implementing those features',
      ],
      technologyUsed: [
        'React',
        'Javascript',
        'Typescript',
        'Spring Boot',
        'Java',
        'GraphQL',
        'Apollo GraphQL',
        'Semantic Versioning',
        'Github',
        'Postman',
        'Insomnia',
        'Microservices',
      ],
    },
    {
      companyName: 'SMS Digital',
      companyLink: 'https://www.sms-digital.com/en/',
      companyLocation: 'Pune, India',
      position: 'Full Stack Developer',
      duration: 'Jul 2020 - May 2021',
      workItems: [
        'Responsible for creating a scalable Product known as Cracks Preventer, heavily involved in creating System Design and architecture from scratch',
        'Developed a real-time alert system to depict ML predictions with 50ms precision using Server sent events and WebSocket APIs',
        'Created backend python services to scale web socket requests, also added user authentication and authorisation',
        'Worked with Product managers and UI/UX Designers to create design standards for the company',
        'Accoladed with Sprint Champion title for 3 consecutive Sprints in 2021 and Best Performer title for Quarter 4 2020',
        'Responsible for taking interviews and making potential hiring decisions',
      ],
      technologyUsed: [
        'Angular',
        'Python',
        'Javascript',
        'Java',
        'FastAPI',
        'SQLAlchemy ORM',
        'WebSockets',
        'Server sent events',
        'AWS',
        'Jenkins',
        'RESTful API',
        'Flask',
        'APScheduler',
        'Celery',
        'Microservices',
        'Docker',
      ],
    },
    {
      companyName: 'SMS Digital',
      companyLink: 'https://www.sms-digital.com/en/',
      companyLocation: 'Pune, India',
      position: 'Full Stack Development Intern',
      duration: 'Feb 2020 – Jun 2020',
      workItems: [
        'Implemented Full Stack Web application for analysis of the throughput of various metals and their grades',
        'Responsible for developing both React Frontend and Python Backend services along with User Authentication',
        'Migrated existing Angular UI to React',
        'Performed analysis on running queries parallelly and concurrently to considerably improve execution time',
      ],
      technologyUsed: [
        'Angular',
        'React',
        'Python',
        'FastAPI',
        'SQLAlchemy ORM',
        'Async Databases',
        'REST',
      ],
    },
    {
      companyName: 'Geeks for Geeks',
      companyLink: 'https://www.geeksforgeeks.org/',
      companyLocation: 'India',
      position: 'Technical Content Writer Intern',
      duration: 'May 2020 – Oct 2020',
      workItems: [
        'Authored articles on a variety of technical topics like Algorithms and Software Development, read by over 100k users to date',
        'Improved quality of existing articles, also fixed incorrect information',
      ],
      technologyUsed: [
        'Angular',
        'Python',
        'FastAPI',
        'Sequelize',
        'Async DB',
        'Atomics CSS',
        'Angular Material',
        'Firebase',
        'ML',
        'Deep Learning',
        'Convolution Neural Network',
      ],
    },
    {
      companyName: 'SMS Digital',
      companyLink: 'https://www.sms-digital.com/en/',
      companyLocation: 'Dusseldorf, Germany',
      position: 'Bachelor’s Project Intern',
      duration: 'Dec 2019 – Feb 2020',
      workItems: [
        'Won an opportunity to work on this project in the Dusseldorf Head Office, Germany for 2 months',
        'Developed Full Stack Web application to perform analysis on Demand Forecast made by ML Models for 10,000 steel-grades',
        'The user can switch ML Models and see the forecasts on time-series data along with model performance',
        'Scheduled Cronjobs to re-train the ML models weekly',
        'Pre-processed and analyzed time-series data',
        'Improved training performance by running multiple queries in parallel',
      ],
      technologyUsed: [
        'Angular',
        'ApexCharts',
        'HighCharts',
        'SCSS',
        'NodeJS',
        'Express',
        'PostgreSQL',
        'node-pg',
        'Sequelize',
        'Python',
        'Docker',
        'Cronjobs',
      ],
    },
    {
      companyName: 'Siemens',
      companyLink: 'https://www.siemens.com/global/en.html',
      companyLocation: 'Pune, India',
      position: 'Summer Intern',
      duration: 'May 2019 – Jul 2019',
      workItems: [
        'Won an opportunity to work in Core Software Developer Team based on Angular Code Sprint',
        'Built a Limit Administration Portal using Siemens Apollo web framework and GraphQL to create workflow between Administrator and Client, ultimately reducing manual support hours by 90%',
        'Using the portal, the Client gets notified when consumed 80% of resources for a service and can request more resources from the admin',
        'An administrator can provide more resources to the requested service',
      ],
      technologyUsed: [
        'Siemens Apollo Web Framework',
        'Angular',
        'Typescript',
        'Gitlab',
        'GraphQL',
        'Microservices',
      ],
    },
  ];

  constructor() { }

  ngOnInit(): void { }
}
